graph TD
    subgraph "波特五力模型"
        A("<b>供应商的议价能力</b><br/>供应商的议价能力") --> C{"<b>现有竞争者的竞争</b><br/>现有竞争者的竞争"};
        B("<b>购买者的议价能力</b><br/>购买者的议价能力") --> C;
        D("<b>新进入者的威胁</b><br/>新进入者的威胁") --> C;
        E("<b>替代品的威胁</b><br/>替代品的威胁") --> C;
    end