graph TD
    subgraph The Five Stages of Design Thinking (d.school Model)
        A(<b>1 Empathize</b><br/><i>Put yourself in their shoes, understand your users</i>) --> B(<b>2 Define</b><br/><i>Clearly define the core user problem</i>);
        B --> C(<b>3 Ideate</b><br/><i>Brainstorm freely, generate many ideas</i>);
        C --> D(<b>4 Prototype</b><br/><i>Hands-on, turn ideas into reality</i>);
        D --> E(<b>5 Test</b><br/><i>Present prototype to users, get real feedback</i>);
        E --> A;
        E --> B;
        E --> C;
    end