graph TD
    subgraph RACI Responsibility Assignment Matrix Role Definitions
        A(<b>R - Responsible</b><br/><i>“The Doer” - The person who actually performs the work</i><br/>- Responsible for the execution of specific tasks<br/>- A task can have multiple Rs) --> B(<b>A - Accountable</b><br/><i>“The Buck Stops Here” - The person ultimately responsible for the outcome</i><br/>- Has final decision-making and veto power over the task<br/>- <b>A task MUST and CAN ONLY have one A</b>);
        B --> C(<b>C - Consulted</b><br/><i>“In the Loop” - People who need to be consulted for two-way communication</i><br/>- Experts or stakeholders who need to be consulted before decisions or during execution<br/>- Provides expert input, is two-way communication);
        C --> D(<b>I - Informed</b><br/><i>“FYI” - People who only need to be informed of the outcome</i><br/>- Stakeholders who need to be informed of the outcome or progress after the task is completed<br/>- Is one-way communication, no feedback required);
    end