graph TD
    subgraph Two Ways of Change
        A(<b>Kaizen</b>) --> A1(<b>Kenmerken:</b><br/>- Kleine, geleidelijke stappen<br/>- Continu<br/>- Volledige participatie<br/>- Weinig risico); 
        A1 --> A2(<b>Effect:</b><br/>Bereikt langdurige, aanzienlijke vooruitgang<br/>door de accumulatie van vele kleine verbeteringen);

        B(<b>Innovatie</b>) --> B1(<b>Kenmerken:</b><br/>- Grote, doorbraakstappen<br/>- Tussenpozen<br/>- Vaak geleid door experts of specifieke teams<br/>- Hoge risico's);
        B1 --> B2(<b>Effect:</b><br/>Bereikt sprongsgewijze, verstoorde ontwikkeling<br/>door technologische of businessmodelrevoluties);
    end
