graph TD
    subgraph Two Ways of Change
        A(<b>Kaizen</b>) --> A1(<b>Đặc điểm:</b><br/>- Bước nhỏ, từ từ<br/>- Liên tục<br/>- Toàn bộ nhân viên tham gia<br/>- Rủi ro thấp); 
        A1 --> A2(<b>Kết quả:</b><br/>Đạt được tiến bộ dài hạn và đáng kể<br/>thông qua việc tích lũy nhiều cải tiến nhỏ);

        B(<b>Đổi mới</b>) --> B1(<b>Đặc điểm:</b><br/>- Bước lớn, đột phá<br/>- Ngắt quãng<br/>- Thường do chuyên gia hoặc nhóm cụ thể dẫn dắt<br/>- Rủi ro cao);
        B1 --> B2(<b>Kết quả:</b><br/>Đạt được phát triển nhảy vọt và phá vỡ<br/>thông qua cách mạng công nghệ hoặc mô hình kinh doanh);
    end
