graph TD
    subgraph Two Ways of Change
        A(<b>Kaizen</b>) --> A1(<b>Egenskaper:</b><br/>- Små, gradvisa steg<br/>- Kontinuerligt<br/>- Full medverkan<br/>- Låg risk); 
        A1 --> A2(<b>Effekt:</b><br/>Uppnår långsiktig, betydande framgång<br/>genom ackumulering av många små förbättringar);

        B(<b>Innovation</b>) --> B1(<b>Egenskaper:</b><br/>- Stora, genombrottssteg<br/>- Oregelbundet<br/>- Ofta ledd av experter eller särskilda team<br/>- Hög risk);
        B1 --> B2(<b>Effekt:</b><br/>Uppnår språngvis, stördande utveckling<br/>genom teknologisk eller affärsmodellsrevolution);
    end
