graph TD
    subgraph Two Ways of Change
        A(<b>Kaizen</b>) --> A1(<b>特徴:</b><br/>- 小さな、段階的なステップ<br/>- 継続的<br/>- 全員参加<br/>- リスクが低い); 
        A1 --> A2(<b>効果:</b><br/>多くの小さな改善の積み重ねにより<br/>長期的に大きな進歩を遂げる);

        B(<b>イノベーション</b>) --> B1(<b>特徴:</b><br/>- 大きな、画期的なステップ<br/>- 断続的<br/>- よく専門家や特定のチームが主導<br/>- 高リスク);
        B1 --> B2(<b>効果:</b><br/>技術的またはビジネスモデルの革命により<br/>飛躍的、破壊的な発展を遂げる);
    end
