graph TD
    subgraph Успешная сессия мозгового штурма
        A(<b>1 Подготовительный этап</b><br/>- Четко определить фокусную проблему<br/>- Собрать разнообразную команду<br/>- Выбрать подходящего ведущего<br/>- Подготовить материалы: белая доска, стикеры) --> B(<b>2 Разминка и объяснение правил</b><br/>- Провести короткое творческое упражнение<br/>- Ведущий повторяет четыре основных принципа);
        B --> C(<b>3 Этап генерации идей</b><br/>- Свободно предлагать идеи вокруг фокусной проблемы<br/>- Ведущий направляет, обеспечивая участие всех<br/>- Строго соблюдать принцип “откладывайте оценку”);
        C --> D(<b>4 Уточнение и группировка идей</b><br/>- После генерации уточнить неясные идеи по одной<br/>- Группировать похожие или связанные идеи<br/>чтобы сформировать “темы” или “категории”);
        D --> E(<b>5 Фильтрация и оценка</b><br/>- Команда совместно устанавливает критерии оценки<br/>- Выбрать несколько самых перспективных идей<br/>путем голосования или другими методами);
    end
