# -*- coding: utf-8 -*-
"""方法论关系图：每篇文章末尾「相关方法论」卡片的数据源。

只按 slug 定义一次，由 postprocess.py 渲染成各语言版本的链接（链接文字取该语言页面的标题），
所以 12 种语言同时生效。关系按「实际工作中会一起用 / 学完这个通常接着学那个」来挑，
而不是简单按分类。每篇 4~5 个，顺序即展示顺序。
"""

# 同一方法论的不同 slug（不同时期写的两篇文章），视为同一篇做 canonical 归并
ALIASES = {
    "five-whys-tutorial": "5-whys-tutorial",
}

RELATED = {
    # ---- 研究方法
    "quantitative-research-tutorial": ["mixed-methods-research-tutorial", "experimental-research-tutorial",
                                       "correlational-research-tutorial", "descriptive-research-tutorial",
                                       "cross-sectional-research-tutorial"],
    "qualitative-research-tutorial": ["mixed-methods-research-tutorial", "grounded-theory-tutorial",
                                      "ethnography-tutorial", "case-study-tutorial", "action-research-tutorial"],
    "mixed-methods-research-tutorial": ["quantitative-research-tutorial", "qualitative-research-tutorial",
                                        "case-study-tutorial", "action-research-tutorial"],
    "experimental-research-tutorial": ["ab-testing-tutorial", "correlational-research-tutorial",
                                       "quantitative-research-tutorial", "longitudinal-research-tutorial"],
    "correlational-research-tutorial": ["experimental-research-tutorial", "descriptive-research-tutorial",
                                        "cross-sectional-research-tutorial", "longitudinal-research-tutorial"],
    "descriptive-research-tutorial": ["correlational-research-tutorial", "cross-sectional-research-tutorial",
                                      "case-study-tutorial", "quantitative-research-tutorial"],
    "cross-sectional-research-tutorial": ["longitudinal-research-tutorial", "descriptive-research-tutorial",
                                          "correlational-research-tutorial", "quantitative-research-tutorial"],
    "longitudinal-research-tutorial": ["cross-sectional-research-tutorial", "experimental-research-tutorial",
                                       "correlational-research-tutorial", "case-study-tutorial"],
    "grounded-theory-tutorial": ["qualitative-research-tutorial", "ethnography-tutorial",
                                 "case-study-tutorial", "action-research-tutorial"],
    "ethnography-tutorial": ["qualitative-research-tutorial", "grounded-theory-tutorial",
                             "empathy-map-tutorial", "gemba-walk-tutorial", "user-persona-tutorial"],
    "case-study-tutorial": ["qualitative-research-tutorial", "ethnography-tutorial",
                            "grounded-theory-tutorial", "mixed-methods-research-tutorial"],
    "action-research-tutorial": ["kaizen-tutorial", "design-thinking-tutorial",
                                 "qualitative-research-tutorial", "grounded-theory-tutorial"],
    # ---- 学习与思维
    "feynman-technique-tutorial": ["cornell-note-taking-tutorial", "first-principles-thinking-tutorial",
                                   "mind-mapping-tutorial", "pyramid-principle-tutorial"],
    "cornell-note-taking-tutorial": ["feynman-technique-tutorial", "mind-mapping-tutorial",
                                     "pomodoro-technique-tutorial", "gtd-tutorial"],
    "first-principles-thinking-tutorial": ["feynman-technique-tutorial", "5-whys-tutorial",
                                           "logic-tree-tutorial", "iceberg-model-tutorial",
                                           "blue-ocean-strategy-tutorial"],
    "pyramid-principle-tutorial": ["scqa-framework-tutorial", "logic-tree-tutorial",
                                   "star-method-tutorial", "orid-focused-conversation-tutorial",
                                   "mind-mapping-tutorial"],
    "logic-tree-tutorial": ["pyramid-principle-tutorial", "5-whys-tutorial", "fishbone-diagram-tutorial",
                            "problem-solving", "mind-mapping-tutorial"],
    "iceberg-model-tutorial": ["system-dynamics-tutorial", "5-whys-tutorial", "fishbone-diagram-tutorial",
                               "first-principles-thinking-tutorial"],
    "system-dynamics-tutorial": ["iceberg-model-tutorial", "fishbone-diagram-tutorial",
                                 "pestel-analysis-tutorial", "balanced-scorecard-tutorial"],
    # ---- 问题解决与决策
    "5-whys-tutorial": ["fishbone-diagram-tutorial", "iceberg-model-tutorial", "problem-solving",
                        "pareto-analysis-tutorial", "gemba-walk-tutorial"],
    "fishbone-diagram-tutorial": ["5-whys-tutorial", "pareto-analysis-tutorial", "six-sigma-tutorial",
                                  "problem-solving", "logic-tree-tutorial"],
    "problem-solving": ["5-whys-tutorial", "fishbone-diagram-tutorial", "logic-tree-tutorial",
                        "gap-analysis-tutorial", "decision-matrix-tutorial"],
    "gap-analysis-tutorial": ["swot-analysis-tutorial", "smart-goals-tutorial", "okr-tutorial",
                              "problem-solving", "balanced-scorecard-tutorial"],
    "gemba-walk-tutorial": ["kaizen-tutorial", "lean-operations-tutorial", "5-whys-tutorial",
                            "ethnography-tutorial"],
    "pareto-analysis-tutorial": ["fishbone-diagram-tutorial", "5-whys-tutorial", "six-sigma-tutorial",
                                 "eisenhower-matrix-tutorial", "decision-matrix-tutorial"],
    "decision-matrix-tutorial": ["cost-benefit-analysis-tutorial", "eisenhower-matrix-tutorial",
                                 "pareto-analysis-tutorial", "six-thinking-hats-tutorial"],
    "cost-benefit-analysis-tutorial": ["decision-matrix-tutorial", "swot-analysis-tutorial",
                                       "balanced-scorecard-tutorial", "mvp-tutorial"],
    "six-thinking-hats-tutorial": ["brainstorming-tutorial", "mind-mapping-tutorial",
                                   "decision-matrix-tutorial", "design-thinking-tutorial"],
    "brainstorming-tutorial": ["mind-mapping-tutorial", "six-thinking-hats-tutorial",
                               "design-thinking-tutorial", "empathy-map-tutorial"],
    "mind-mapping-tutorial": ["brainstorming-tutorial", "cornell-note-taking-tutorial",
                              "logic-tree-tutorial", "feynman-technique-tutorial"],
    # ---- 战略
    "porters-five-forces-tutorial": ["pestel-analysis-tutorial", "swot-analysis-tutorial",
                                     "value-chain-analysis-tutorial", "blue-ocean-strategy-tutorial"],
    "pestel-analysis-tutorial": ["porters-five-forces-tutorial", "swot-analysis-tutorial",
                                 "gap-analysis-tutorial", "system-dynamics-tutorial"],
    "swot-analysis-tutorial": ["pestel-analysis-tutorial", "porters-five-forces-tutorial",
                               "gap-analysis-tutorial", "business-model-canvas-tutorial", "okr-tutorial"],
    "value-chain-analysis-tutorial": ["porters-five-forces-tutorial", "business-model-canvas-tutorial",
                                      "lean-operations-tutorial", "blue-ocean-strategy-tutorial"],
    "blue-ocean-strategy-tutorial": ["porters-five-forces-tutorial", "business-model-canvas-tutorial",
                                     "lean-canvas-tutorial", "design-thinking-tutorial"],
    "balanced-scorecard-tutorial": ["okr-tutorial", "kpi-tutorial", "smart-goals-tutorial",
                                    "swot-analysis-tutorial", "intro-to-esg-reporting"],
    "business-model-canvas-tutorial": ["value-proposition-canvas-tutorial", "lean-canvas-tutorial",
                                       "value-chain-analysis-tutorial", "blue-ocean-strategy-tutorial",
                                       "swot-analysis-tutorial"],
    "lean-canvas-tutorial": ["lean-startup-tutorial", "business-model-canvas-tutorial", "mvp-tutorial",
                             "value-proposition-canvas-tutorial", "user-persona-tutorial"],
    # ---- 目标与效率
    "okr-tutorial": ["kpi-tutorial", "smart-goals-tutorial", "balanced-scorecard-tutorial",
                     "gap-analysis-tutorial"],
    "kpi-tutorial": ["okr-tutorial", "balanced-scorecard-tutorial", "smart-goals-tutorial",
                     "pareto-analysis-tutorial"],
    "smart-goals-tutorial": ["okr-tutorial", "kpi-tutorial", "gtd-tutorial", "tiny-habits-tutorial"],
    "gtd-tutorial": ["eisenhower-matrix-tutorial", "pomodoro-technique-tutorial",
                     "cornell-note-taking-tutorial", "smart-goals-tutorial"],
    "eisenhower-matrix-tutorial": ["gtd-tutorial", "pomodoro-technique-tutorial",
                                   "pareto-analysis-tutorial", "decision-matrix-tutorial"],
    "pomodoro-technique-tutorial": ["gtd-tutorial", "eisenhower-matrix-tutorial", "tiny-habits-tutorial",
                                    "the-habit-loop-tutorial"],
    "the-habit-loop-tutorial": ["tiny-habits-tutorial", "pomodoro-technique-tutorial",
                                "smart-goals-tutorial", "kaizen-tutorial"],
    "tiny-habits-tutorial": ["the-habit-loop-tutorial", "kaizen-tutorial", "smart-goals-tutorial",
                             "pomodoro-technique-tutorial"],
    # ---- 沟通协作
    "sbi-feedback-model-tutorial": ["orid-focused-conversation-tutorial", "star-method-tutorial",
                                    "after-action-review-tutorial", "raci-matrix-tutorial"],
    "orid-focused-conversation-tutorial": ["after-action-review-tutorial", "sbi-feedback-model-tutorial",
                                           "six-thinking-hats-tutorial", "brainstorming-tutorial"],
    "raci-matrix-tutorial": ["okr-tutorial", "scrum-tutorial", "kanban-tutorial",
                             "sbi-feedback-model-tutorial"],
    # ---- 产品与用户
    "design-thinking-tutorial": ["empathy-map-tutorial", "user-journey-map-tutorial", "user-persona-tutorial",
                                 "mvp-tutorial", "brainstorming-tutorial"],
    "empathy-map-tutorial": ["user-persona-tutorial", "user-journey-map-tutorial",
                             "design-thinking-tutorial", "ethnography-tutorial"],
    "user-persona-tutorial": ["empathy-map-tutorial", "user-journey-map-tutorial",
                              "kano-model-tutorial", "design-thinking-tutorial"],
    "user-journey-map-tutorial": ["user-persona-tutorial", "empathy-map-tutorial",
                                  "usability-testing-tutorial", "design-thinking-tutorial"],
    "usability-testing-tutorial": ["ab-testing-tutorial", "user-journey-map-tutorial", "mvp-tutorial",
                                   "design-thinking-tutorial"],
    "ab-testing-tutorial": ["experimental-research-tutorial", "mvp-tutorial",
                            "usability-testing-tutorial", "lean-canvas-tutorial"],
    "mvp-tutorial": ["lean-startup-tutorial", "lean-canvas-tutorial", "ab-testing-tutorial",
                     "kano-model-tutorial", "design-thinking-tutorial"],
    # 只有英文版的页面挂在相关条目末尾：其他语言缺目标时自动跳过
    "agile-tutorial": ["scrum-tutorial", "kanban-tutorial", "mvp-tutorial", "design-thinking-tutorial",
                       "hybrid-project-management-playbook", "agile-roi-calculator"],
    "scrum-tutorial": ["agile-tutorial", "kanban-tutorial", "raci-matrix-tutorial", "okr-tutorial"],
    "kanban-tutorial": ["scrum-tutorial", "agile-tutorial", "lean-operations-tutorial", "gtd-tutorial",
                        "intro-to-devops"],
    "agile-roi-calculator": ["agile-tutorial", "scrum-tutorial", "cost-benefit-analysis-tutorial"],
    "hybrid-project-management-playbook": ["agile-tutorial", "scrum-tutorial", "kanban-tutorial",
                                           "raci-matrix-tutorial"],
    "intro-to-devops": ["agile-tutorial", "kanban-tutorial", "lean-operations-tutorial", "scrum-tutorial"],
    "intro-to-esg-reporting": ["balanced-scorecard-tutorial", "kpi-tutorial", "pestel-analysis-tutorial",
                               "value-chain-analysis-tutorial"],
    # ---- 质量与运营
    "kaizen-tutorial": ["pdca-cycle-tutorial", "lean-operations-tutorial", "six-sigma-tutorial",
                        "gemba-walk-tutorial", "value-stream-mapping-tutorial"],
    "lean-operations-tutorial": ["value-stream-mapping-tutorial", "kaizen-tutorial", "six-sigma-tutorial",
                                 "kanban-tutorial", "pdca-cycle-tutorial"],
    "six-sigma-tutorial": ["total-quality-management-tutorial", "pdca-cycle-tutorial",
                           "fishbone-diagram-tutorial", "pareto-analysis-tutorial"],
    "total-quality-management-tutorial": ["six-sigma-tutorial", "kaizen-tutorial",
                                          "lean-operations-tutorial", "fishbone-diagram-tutorial"],
    # ---- 新增方法论（2026-10）
    "pdca-cycle-tutorial": ["kaizen-tutorial", "total-quality-management-tutorial",
                            "lean-operations-tutorial", "six-sigma-tutorial",
                            "after-action-review-tutorial"],
    "value-stream-mapping-tutorial": ["lean-operations-tutorial", "kaizen-tutorial",
                                      "gemba-walk-tutorial", "kanban-tutorial",
                                      "pdca-cycle-tutorial"],
    "after-action-review-tutorial": ["orid-focused-conversation-tutorial", "5-whys-tutorial",
                                     "pdca-cycle-tutorial", "sbi-feedback-model-tutorial",
                                     "scrum-tutorial"],
    "star-method-tutorial": ["scqa-framework-tutorial", "sbi-feedback-model-tutorial",
                             "pyramid-principle-tutorial", "after-action-review-tutorial",
                             "smart-goals-tutorial"],
    "lean-startup-tutorial": ["mvp-tutorial", "lean-canvas-tutorial",
                              "value-proposition-canvas-tutorial", "ab-testing-tutorial",
                              "design-thinking-tutorial"],
    "kano-model-tutorial": ["value-proposition-canvas-tutorial", "user-persona-tutorial",
                            "decision-matrix-tutorial", "mvp-tutorial",
                            "ab-testing-tutorial"],
    "value-proposition-canvas-tutorial": ["business-model-canvas-tutorial", "lean-canvas-tutorial",
                                          "kano-model-tutorial", "empathy-map-tutorial",
                                          "lean-startup-tutorial"],
    "scqa-framework-tutorial": ["pyramid-principle-tutorial", "star-method-tutorial",
                                "logic-tree-tutorial", "after-action-review-tutorial"],
}

HEADING = {
    "en": "Related methodologies", "zh": "相关方法论", "ja": "関連する方法論",
    "ko": "관련 방법론", "es": "Metodologías relacionadas", "fr": "Méthodologies associées",
    "de": "Verwandte Methoden", "pt": "Metodologias relacionadas", "ru": "Связанные методологии",
    "nl": "Gerelateerde methodologieën", "sv": "Relaterade metoder", "vi": "Phương pháp liên quan",
}
