graph TD
    A(Lợi Nhuận Nhà Hàng Giảm) --> B(Doanh Thu Giảm)
    A --> C(Chi Phí Tăng)

    B --> D(Số Khách Hàng Giảm)
    B --> E(Trung Bình Chi Tiêu Trên Mỗi Khách Giảm)

    C --> F(Chi Phí Thực Phẩm Tăng)
    C --> G(Chi Phí Vận Hành Tăng)

    G --> H(Chi Phí Nhân Công Tăng)
    G --> I(Chi Phí Thuê Mặt Bằng/Tiện Ích Tăng)
