graph TD
    A[1 Formulate Causal Hypothesis] --> B(2 Recruit Research Participants);
    B --> C{3 Randomly Assign Participants};
    C --> D(<b>Experimental Group</b><br/>Receives treatment/intervention);
    C --> E(<b>Control Group</b><br/>Receives no treatment/placebo);
    D --> F(4 Implement Independent Variable Manipulation);
    E --> F;
    F --> G(5 Measure Dependent Variable for All Groups);
    G --> H(6 Statistical Analysis Group Differences);
    H --> I{7 Test Hypothesis, Draw Causal Conclusion};