graph TD
    subgraph The Habit Loop
        A(<b>1. Cue / Trigger</b><br/><i>A signal that triggers the brain to enter "automatic mode"</i><br/>- It can be anything: a specific <b>time</b>,<br/>a <b>place</b>, an <b>emotion</b>, a group of <b>specific people</b>,<br/>or a <b>preceding action</b>.) --> B(<b>2. Routine</b><br/><i>The behavior you unconsciously perform</i><br/>- This is the actual, visible habitual behavior you exhibit,<br/>which can be physical, mental, or emotional.);
        B --> C(<b>3. Reward</b><br/><i>The pleasure that makes your brain "love" this loop</i><br/>- The positive feedback from the behavior, which tells your brain:<br/>"This loop is worth remembering and repeating.");
        C --> A;
    end