graph TD
    subgraph Two Ways of Change
        A(<b>Kaizen</b>) --> A1(<b>Características:</b><br/>- Pequenos passos graduais<br/>- Contínuo<br/>- Participação total<br/>- Baixo risco); 
        A1 --> A2(<b>Efeito:</b><br/>Alcança progresso significativo e de longo prazo<br/>através do acúmulo de muitas pequenas melhorias);

        B(<b>Inovação</b>) --> B1(<b>Características:</b><br/>- Grandes passos e avanços<br/>- Intermitente<br/>- Frequentemente liderado por especialistas ou equipes específicas<br/>- Alto risco);
        B1 --> B2(<b>Efeito:</b><br/>Alcança desenvolvimento disruptivo e por saltos<br/>por meio de revolução tecnológica ou de modelo de negócios);
    end
