graph TD
    A(<b>Центральная тема</b><br/>например, Успешная вечеринка на день рождения) --> B(<b>Основная ветвь 1: Гости</b>);
    A --> C(<b>Основная ветвь 2: Еда</b>);
    A --> D(<b>Основная ветвь 3: Активность</b>);
    A --> E(<b>Основная ветвь 4: Место</b>);

    B --> B1(Ветвь: Семья);
    B --> B2(Ветвь: Друзья);
    B2 --> B2a(Подветвь: Сокурсники);
    B2 --> B2b(Подветвь: Коллеги);

    C --> C1(Ветвь: Торт);
    C --> C2(Ветвь: Напитки);
    C --> C3(Ветвь: Основное блюдо);

    D --> D1(Ветвь: Музыка);
    D --> D2(Ветвь: Игры);

    E --> E1(Ветвь: Бронирование);
    E --> E2(Ветвь: Украшения);
