graph TD
    subgraph Two Ways of Change
        A(<b>Kaizen</b>) --> A1(<b>Merkmale:</b><br/>- Kleine, schrittweise Schritte<br/>- Kontinuierlich<br/>- Vollständige Beteiligung<br/>- Geringes Risiko); 
        A1 --> A2(<b>Wirkung:</b><br/>Erreicht langfristige, bedeutende Fortschritte<br/>durch die Akkumulation vieler kleiner Verbesserungen);

        B(<b>Innovation</b>) --> B1(<b>Merkmale:</b><br/>- Große, bahnbrechende Schritte<br/>- Gelegentlich<br/>- Wird oft von Experten oder speziellen Teams geleitet<br/>- Hohes Risiko);
        B1 --> B2(<b>Wirkung:</b><br/>Erreicht sprunghafte, disruptive Entwicklung<br/>durch technologische oder Geschäftsmodell-Revolution);
    end
