graph TD
    subgraph Porter's Five Forces Model
        A(<b>Bargaining Power of Suppliers</b><br/>Bargaining Power of Suppliers) --> C{<b>Rivalry Among<br/>Existing Competitors</b><br/>Rivalry Among<br/>Existing Competitors};
        B(<b>Bargaining Power of Buyers</b><br/>Bargaining Power of Buyers) --> C;
        D(<b>Threat of New Entrants</b><br/>Threat of New Entrants) --> C;
        E(<b>Threat of Substitutes</b><br/>Threat of Substitutes) --> C;
    end