graph TD
    subgraph Lean Canvas
        direction LR
        subgraph Product
            S(<b>3. Решение</b><br/><i>Как мы решаем эти проблемы?</i>)
            P(<b>1. Проблема</b><br/><i>Какие 1-3 главные проблемы у клиентов?</i>)
            UVP(<b>4. Уникальное торговое предложение</b><br/><i>Почему мы уникальны?</i>)
            KM(<b>8. Ключевые метрики</b><br/><i>Как мы измеряем успех?</i>)
        end

        subgraph Market
            UA(<b>9. Несправедливое преимущество</b><br/><i>Какие у нас есть преимущества, которые трудно скопировать?</i>)
            CH(<b>5. Каналы</b><br/><i>Как мы достигаем клиентов?</i>)
            CS(<b>2. Сегмент клиентов</b><br/><i>Кто наши целевые клиенты?</i>)
        end

        P & S --> UVP;
        UVP --> CH & CS;

        subgraph Finances
            C(<b>7. Структура затрат</b><br/><i>Где наши расходы?</i>)
            R(<b>6. Потоки доходов</b><br/><i>Как мы зарабатываем деньги?</i>)
        end

        product -- Создает --> C;
        market -- Создает --> R;
    end
