graph TD
    subgraph Four Actions Framework
            A(<b>Éliminer</b><br/>Quels facteurs que l'industrie considère comme allant de soi<br/>devraient être complètement éliminés ?) --> B(<b>Réduire</b><br/>À quels niveaux d'investissement devrait-on<br/>descendre bien en dessous de la norme industrielle ?);
            B --> C(<b>Augmenter</b><br/>À quels niveaux d'investissement devrait-on<br/>monter bien au-dessus de la norme industrielle ?);
            C --> D(<b>Créer</b><br/>Quels nouveaux facteurs, jamais offerts<br/>par l'industrie auparavant, devraient être créés ?);
        end
