graph TD
    subgraph SBI反馈模型的结构
        A(<b>S - 情境</b><br/><i>什么时候和在哪里？</i><br/>- 清楚地指出具体的<br/>反馈所指的时间和场景) --> B(<b>B - 行为</b><br/><i>你具体做了什么/说了什么？</i><br/>- 客观地、非评判性地描述<br/>可观察的、具体的行为或言语);
        B --> C(<b>I - 影响</b><br/><i>你的行为对我/我们产生了什么影响？</i><br/>- 清楚地表达具体的、真实的影响或感受<br/>那种行为对你或他人产生的影响);
    end