site_name: "Wiki da Sabedoria das Metodologias : Caminho para o Sucesso"
site_description: 'Uma base de conhecimento dedicada à introdução, explicação e aplicação sistemática de várias metodologias poderosas, ajudando as pessoas em seu caminho para o sucesso.'
site_author: 'methodologywiki'

site_url: https://methodologywiki.com/pt/
repo_url: https://github.com/mayunlei/methodologywiki

docs_dir: docs

theme:
  name: material
  font: false
  custom_dir: ../overrides
  language: pt
  favicon: ../favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-VQ6RTZVF1S
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
    - name: Español
      link: /es/
      lang: es
    - name: 日本語
      link: /ja/
      lang: ja
    - name: 한국어
      link: /ko/
      lang: ko
    - name: Русский
      link: /ru/
      lang: ru
    - name: Français
      link: /fr/
      lang: fr
    - name: Deutsch
      link: /de/
      lang: de
    - name: Português
      link: /pt/
      lang: pt
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: Tiếng Việt
      link: /vi/
      lang: vi
    - name: Svenska
      link: /sv/
      lang: sv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2:
      version: 10.0.2

nav:
  - 'Início': 'index.md'
  - 'Fundamentos':
    - 'Disciplinas Básicas':
      - 'Pesquisa de Métodos Mistos': 'Foundations/basic_discipline/Mixed-Methods-Research-Tutorial-pt.md'
      - 'Pesquisa Qualitativa': 'Foundations/basic_discipline/Qualitative-Research-Tutorial-pt.md'
      - 'Pesquisa Quantitativa': 'Foundations/basic_discipline/Quantitative-Research-Tutorial-pt.md'
    - 'Métodos de Aprendizagem':
      - 'Método Cornell': 'Foundations/learning_methods/Cornell-Note-Taking-Tutorial-pt.md'
      - 'Técnica Feynman': 'Foundations/learning_methods/Feynman-Technique-Tutorial-pt.md'
    - 'Pensamento Lógico':
      - 'Pensamento de Primeiros Princípios': 'Foundations/logical_thinking/First-Principles-Thinking-Tutorial-pt.md'
      - 'Princípio da Pirâmide': 'Foundations/logical_thinking/Pyramid-Principle-Tutorial-pt.md'
    - 'Paradigma de Investigação Científica':
      - 'Pesquisa Correlacional': 'Foundations/scientific_inquiry_paradigm/Correlational-Research-Tutorial-pt.md'
      - 'Pesquisa Descritiva': 'Foundations/scientific_inquiry_paradigm/Descriptive-Research-Tutorial-pt.md'
      - 'Pesquisa Experimental': 'Foundations/scientific_inquiry_paradigm/Experimental-Research-Tutorial-pt.md'
    - 'Pensamento Sistêmico':
      - 'Modelo do Iceberg': 'Foundations/systems_thinking/Iceberg-Model-Tutorial-pt.md'
      - 'Dinâmica de Sistemas': 'Foundations/systems_thinking/System-Dynamics-Tutorial-pt.md'
    - 'Teoria e Prática':
      - 'Pesquisa-Ação': 'Foundations/theory_and_practice/Action-Research-Tutorial-pt.md'
      - 'Teoria Fundamentada': 'Foundations/theory_and_practice/Grounded-Theory-Tutorial-pt.md'
  - 'Estratégia e Negócios':
    - 'Modelo de Negócio':
      - 'Canvas do Modelo de Negócio': 'Strategy & Business/business_model/Business-Model-Canvas-Tutorial-pt.md'
      - 'Canvas Lean': 'Strategy & Business/business_model/Lean-Canvas-Tutorial-pt.md'
    - 'Qualidade e Operações':
      - 'Kaizen': 'Strategy & Business/quality_and_operations/Kaizen-Tutorial-pt.md'
      - 'Operações Lean': 'Strategy & Business/quality_and_operations/Lean-Operations-Tutorial-pt.md'
      - 'Six Sigma': 'Strategy & Business/quality_and_operations/Six-Sigma-Tutorial-pt.md'
      - 'Gestão da Qualidade Total': 'Strategy & Business/quality_and_operations/Total-Quality-Management-Tutorial-pt.md'
    - 'Análise Estratégica':
      - 'Análise PESTEL': 'Strategy & Business/strategic_analysis/PESTEL-Analysis-Tutorial-pt.md'
      - 'Cinco Forças de Porter': 'Strategy & Business/strategic_analysis/Porters-Five-Forces-Tutorial-pt.md'
      - 'Análise SWOT': 'Strategy & Business/strategic_analysis/SWOT-Analysis-Tutorial-pt.md'
      - 'Análise da Cadeia de Valor': 'Strategy & Business/strategic_analysis/Value-Chain-Analysis-Tutorial-pt.md'
    - 'Execução Estratégica':
      - 'Balanced Scorecard': 'Strategy & Business/strategic_execution/Balanced-Scorecard-Tutorial-pt.md'
      - 'Estratégia do Oceano Azul': 'Strategy & Business/strategic_execution/Blue-Ocean-Strategy-Tutorial-pt.md'
  - 'Resolução de Problemas e Tomada de Decisão':
    - 'Tomada de Decisão':
      - 'Análise Custo-Benefício': 'Problem Solving & Decision Making/decision_making/Cost-Benefit-Analysis-Tutorial-pt.md'
      - 'Matriz de Decisão': 'Problem Solving & Decision Making/decision_making/Decision-Matrix-Tutorial-pt.md'
      - 'Análise de Pareto': 'Problem Solving & Decision Making/decision_making/Pareto-Analysis-Tutorial-pt.md'
    - 'Geração de Ideias':
      - 'Brainstorming': 'Problem Solving & Decision Making/ideation/Brainstorming-Tutorial-pt.md'
      - 'Mapa Mental': 'Problem Solving & Decision Making/ideation/Mind-Mapping-Tutorial-pt.md'
      - 'Seis Chapéus do Pensamento': 'Problem Solving & Decision Making/ideation/Six-Thinking-Hats-Tutorial-pt.md'
    - 'Resolução de Problemas':
      - 'Análise de Lacunas': 'Problem Solving & Decision Making/problem_solving/Gap-Analysis-Tutorial-pt.md'
      - 'Caminhada Gemba': 'Problem Solving & Decision Making/problem_solving/Gemba-Walk-Tutorial-pt.md'
      - 'Árvore Lógica': 'Problem Solving & Decision Making/problem_solving/Logic-Tree-Tutorial-pt.md'
      - 'Resolução de Problemas': 'Problem Solving & Decision Making/problem_solving/Problem-Solving-pt.md'
    - 'Análise de Causa Raiz':
      - 'Cinco Porquês': 'Problem Solving & Decision Making/root_cause_analysis/5-Whys-Tutorial-pt.md'
      - 'Diagrama de Espinha de Peixe': 'Problem Solving & Decision Making/root_cause_analysis/Fishbone-Diagram-Tutorial-pt.md'
  - 'Produto e Usuário':
    - 'Desenvolvimento de Produtos':
      - 'Agile': 'Product & User/product_development/Agile-Tutorial-pt.md'
      - 'Design Thinking': 'Product & User/product_development/Design-Thinking-Tutorial-pt.md'
      - 'Kanban': 'Product & User/product_development/Kanban-Tutorial-pt.md'
      - 'Scrum': 'Product & User/product_development/Scrum-Tutorial-pt.md'
    - 'Métodos Qualitativos Especializados':
      - 'Estudo de Caso': 'Product & User/specialized_qualitative_methods/Case-Study-Tutorial-pt.md'
      - 'Etnografia': 'Product & User/specialized_qualitative_methods/Ethnography-Tutorial-pt.md'
    - 'Teste e Validação':
      - 'Teste A/B': 'Product & User/testing_and_validation/AB-Testing-Tutorial-pt.md'
      - 'MVP': 'Product & User/testing_and_validation/MVP-Tutorial-pt.md'
      - 'Teste de Usabilidade': 'Product & User/testing_and_validation/Usability-Testing-Tutorial-pt.md'
    - 'Design de Dimensão Temporal':
      - 'Pesquisa Transversal': 'Product & User/time_dimension_design/Cross-Sectional-Research-Tutorial-pt.md'
      - 'Pesquisa Longitudinal': 'Product & User/time_dimension_design/Longitudinal-Research-Tutorial-pt.md'
    - 'Pesquisa do Usuário':
      - 'Mapa de Empatia': 'Product & User/user_research/Empathy-Map-Tutorial-pt.md'
      - 'Mapa da Jornada do Usuário': 'Product & User/user_research/User-Journey-Map-Tutorial-pt.md'
      - 'Persona do Usuário': 'Product & User/user_research/User-Persona-Tutorial-pt.md'
  - 'Produtividade Pessoal e de Equipe':
    - 'Técnicas de Feedback':
      - 'Modelo de Feedback SBI': 'Personal & Team Productivity/feedback_techniques/SBI-Feedback-Model-Tutorial-pt.md'
    - 'Gestão de Objetivos':
      - 'KPI': 'Personal & Team Productivity/goal_management/KPI-Tutorial-pt.md'
      - 'OKR': 'Personal & Team Productivity/goal_management/OKR-Tutorial-pt.md'
      - 'Objetivos SMART': 'Personal & Team Productivity/goal_management/SMART-Goals-Tutorial-pt.md'
    - 'Formação de Hábitos':
      - 'O Loop do Hábito': 'Personal & Team Productivity/habit_formation/The-Habit-Loop-Tutorial-pt.md'
      - 'Micro-Hábitos': 'Personal & Team Productivity/habit_formation/Tiny-Habits-Tutorial-pt.md'
    - 'Eficácia de Reuniões':
      - 'Conversa Focada ORID': 'Personal & Team Productivity/meeting_effectiveness/ORID-Focused-Conversation-Tutorial-pt.md'
    - 'Colaboração de Equipe':
      - 'Matriz RACI': 'Personal & Team Productivity/team_collaboration/RACI-Matrix-Tutorial-pt.md'
    - 'Gestão do Tempo':
      - 'Matriz de Eisenhower': 'Personal & Team Productivity/time_management/Eisenhower-Matrix-Tutorial-pt.md'
      - 'GTD': 'Personal & Team Productivity/time_management/GTD-Tutorial-pt.md'
      - 'Técnica Pomodoro': 'Personal & Team Productivity/time_management/Pomodoro-Technique-Tutorial-pt.md'

