graph TD
    subgraph Business Model Canvas
        direction LR
        subgraph Infrastructure
            KP(<b>8. Key Partnerships</b><br/><i>Who can help us?</i>)
            KA(<b>7. Key Activities</b><br/><i>What do we need to do?</i>)
            KR(<b>6. Key Resources</b><br/><i>What do we need?</i>)
        end

        subgraph Offering
            VP(<b>1. Value Propositions</b><br/><i>What value do we offer?</i>)
        end

        subgraph Customers
            CR(<b>4. Customer Relationships</b><br/><i>How do we interact?</i>)
            CH(<b>3. Channels</b><br/><i>How do we reach customers?</i>)
            CS(<b>2. Customer Segments</b><br/><i>Who do we serve?</i>)
        end

        KP & KA & KR --> VP;
        VP --> CR & CH & CS;

        subgraph Finances
            C(<b>9. Cost Structure</b><br/><i>What are our costs?</i>)
            R(<b>5. Revenue Streams</b><br/><i>How do we make money?</i>)
        end

        infrastructure -- Generates --> C;
        customers -- Generates --> R;
    end