graph TD
    subgraph A Successful Brainstorming Session
        A(<b>1 Förberedelsefas</b><br/>- Definiera tydligt fokuseringsproblem<br/>- Samla ett varierat team<br/>- Välj en lämplig facilitator<br/>- Förbered material: whiteboard, post-it-lappar) --> B(<b>2 Uppvärmning och regelförklaring</b><br/>- Genomför en kort kreativ uppvärmningsaktivitet<br/>- Facilitatorn förklarar de fyra grundläggande principerna på nytt);
        B --> C(<b>3 Idégenereringsfas</b><br/>- Fritt föreslå idéer kring fokuseringsproblemet<br/>- Facilitator leder och säkerställer att alla deltar<br/>- Följ strikt principen om “uppskjutande av bedömning”);
        C --> D(<b>4 Idéklarering och gruppering</b><br/>- Efter generering, klargör oklara idéer en i taget<br/>- Gruppera liknande eller relaterade idéer<br/>för att bilda “teman” eller “kategorier”);
        D --> E(<b>5 Filtrering och utvärdering</b><br/>- Teamet sätter tillsammans utvärderingskriterier<br/>- Välj de mest lovande idéerna<br/>genom omröstning eller andra metoder);
    end
