graph TD
    subgraph Два пути изменений
        A(<b>Кайдзен</b>) --> A1(<b>Характеристики:</b><br/>- Маленькие, постепенные шаги<br/>- Непрерывность<br/>- Всеобщее участие<br/>- Низкий риск); 
        A1 --> A2(<b>Эффект:</b><br/>Долгосрочный, значительный прогресс<br/>достигается за счет накопления множества мелких улучшений);

        B(<b>Инновации</b>) --> B1(<b>Характеристики:</b><br/>- Крупные, прорывные шаги<br/>- Периодичность<br/>- Часто инициируются экспертами или конкретными командами<br/>- Высокий риск);
        B1 --> B2(<b>Эффект:</b><br/>Достигается скачкообразное, деструктивное развитие<br/>посредством технологической или бизнес-революции);
    end
