graph TD
    subgraph 成本效益分析
        A[<b>一个项目或决策</b>] --> B[<b>总成本</b>]
        A --> C[<b>总收益</b>]

        subgraph 成本类型
            B --> B1[<b>直接成本</b><br/>- 硬件/软件采购<br/>- 人员薪资<br/>- 原材料成本]
            B --> B2[<b>间接成本</b><br/>- 办公室租金分摊<br/>- 水电费<br/>- 行政管理费用]
            B --> B3[<b>无形成本</b><br/>- 员工士气下降<br/>- 客户满意度降低<br/>- 品牌声誉受损]
            B --> B4[<b>机会成本</b><br/>- 因选择本项目而放弃的<br/>其他投资机会的潜在收益]
        end

        subgraph 收益类型
            C --> C1[<b>直接收益</b><br/>- 销售收入增加<br/>- 成本节约]
            C --> C2[<b>间接收益</b><br/>- 生产效率提高<br/>- 资产价值增加]
            C --> C3[<b>无形收益</b><br/>- 客户满意度提升<br/>- 品牌形象增强<br/>- 员工满意度提高]
            C --> C4[<b>战略收益</b><br/>- 市场份额扩大<br/>- 竞争优势增强]
        end
    end