graph TD
    subgraph 冰山模型
        direction TB
        A(事件层级<br/>发生了什么?<br/>我们观察到的孤立现象) -- 深化思考 --> B(模式层级<br/>过去出现了什么趋势?<br/>由重复出现的事件形成的趋势和模式);
        B -- 深化思考 --> C(结构层级<br/>是什么导致了这些模式?<br/>导致模式出现的系统内部的相互关系和结构);
        C -- 深化思考 --> D(心智模型层级<br/>我们对此有何信念和假设?<br/>支撑整个系统结构运作的根深蒂固的信念、价值观和假设);

        subgraph 水上
            A
        end
        subgraph 水下
            B
            C
            D
        end

        note right of A: 行动：反应式
        note right of B: 行动：预期/适应性
        note right of C: 行动：设计/创造性
        note right of D: 行动：变革性
    end